### ISSUE TITLE
Release the library under a suitable, preferably Open Source, license

### ISSUE THREAD

**Issue by Kakurady** [zuoanqh/UIAL-UTAU-Interfacing-API-Library#3]
Please release the library under a license suitable for legally integrating it into a larger application. 请将库在适合将它合法整合到应用程序中的许可协议下发布。

With the current proprietary license, I can't even make a pull request without violating copyright. 按当前的专有协议，想创建拉取请求而不违反版权都不行。

**Comment by zuoanqh** [comment]
I'm currently under deadline for a paper, so not now. However, I promise to release the library within a month, under MIT license.

I did not authorize redistribution, because I am yet to make sure, that I have all the rights to redistribute everything here.

Thanks for your attention to this issue. :)

Note: While I speak natively in Chinese, I prefer communications in English here, so it is easier for everyone else to understand.

**Comment by Kakurady** [comment]
Thank you very much for your fast response!

**Comment by zuoanqh** [comment]
Annnnd it's nearly 2 months. Just changed the license so everyone could use it now. Have fun!
